Жанры, Категории и Произведения — модели, view и эндпоинты
sonjpog/api_yamdb pull request #4
Opened 2024-10-09 15:00 UTC by sonjpog

Ребята, я сделала: 
1. Прописала модели Genre, Category, Title. 
2. Создала отдельные файлы для констант и валидаторов в приложении reviews. 
3. Добавила приложение api в основные urls
4. В приложении api сделала отдельные файлы для фильтра, миксинов и сериализаторов. 
5. В приложении reviews зарегистрировала «свои» модели (вы можете внести свои). 
6. Прописала сериализаторы и функции для своих моделей, но не добавляла пермишн классы. 

В общем, кажется, сделала почти всё по своей части, чтобы от этого можно было отталкиваться тоже, когда сольём ветки. Жду комментов!)

2024-10-09 18:26 UTC, ValentinSmir approved these changes

2024-10-09 19:35 UTC, LeonidZ92 requested changes
Посмотрел, добавил небольшие комментарии

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api_yamdb/settings.py
>      'django.contrib.staticfiles',
стоит добавить 'django_filters' в список INSTALLED_APPS, чтобы он корректно импортировался

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api/filters.py
> +import django_filters as filters
стоит зарегать django_filters в INSTALLED_APPS

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api/serializers.py
> +class TitleСhangeSerializer(serializers.ModelSerializer):
в названии модели использована кириллица. Нужно переписать "C" с английской раскладкой

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api/serializers.py
> +        lookup_field = 'slug'
lookup_field — это параметр, который используется в представлениях (Views) для поиска объектов по полю, отличному от id. В Meta классе сериализаторам этот параметр не нужен. Стоит убрать

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api/serializers.py
> +        lookup_field = 'slug'
lookup_field — это параметр, который используется в представлениях (Views) для поиска объектов по полю, отличному от id. В Meta классе сериализаторам этот параметр не нужен. Стоит убрать

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api/urls.py
> +router_v1.register('genres', GenreViewSet, basename='genres')
не хватает:
urlpatterns = [
    path('v1/', include(router_v1.urls)),

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api/views.py
> +                          TitleСhangeSerializer,
кириллица в названии

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api/views.py
> +            return TitleСhangeSerializer
кириллица в названии

2024-10-09 19:35 UTC, LeonidZ92 commented on api_yamdb/api_yamdb/urls.py
> -from django.urls import path
лишняя строчка

2024-10-10 07:36 UTC, sonjpog commented on api_yamdb/api_yamdb/urls.py
> -from django.urls import path
Тут не очень поняла, к чему комментарий

2024-10-10 07:47 UTC, LeonidZ92 commented on api_yamdb/api_yamdb/urls.py
> -from django.urls import path
у тебя ниже уже path импортируется

2024-10-10 07:49 UTC, LeonidZ92 approved these changes
гуд джоб!

2024-10-10 08:47 UTC, merged